version: "3.9"
   
services:
  db:
    container_name: research_portal_db
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata_prod/db:/var/lib/postgresql/data

  api:
    container_name: research_portal_api
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
