# Generated by Django 3.2.4 on 2021-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
