# Generated by Django 3.2.4 on 2021-08-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_aor_id_project_aor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmemberrelationship',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectmemberrelationship',
            old_name='user_id',
            new_name='user',
        ),
    ]
