# Generated by Django 3.2.4 on 2021-08-20 19:25

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210820_1312'),
    ]

    operations = [
        UnaccentExtension()
    ]
