# Generated by Django 3.2.4 on 2021-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210820_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofresearch',
            name='slug',
        ),
        migrations.AddField(
            model_name='areaofresearch',
            name='description',
            field=models.TextField(default='something', max_length=10000.0),
            preserve_default=False,
        ),
    ]
