# Generated by Django 3.2.4 on 2021-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210820_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
