# Generated by Django 3.2.4 on 2021-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210827_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
