# Generated by Django 3.2.4 on 2021-09-08 14:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_department_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='COE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000.0)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='aor',
        ),
        migrations.AddField(
            model_name='project',
            name='aor_tags',
            field=models.ManyToManyField(to='api.AreaOfResearch'),
        ),
        migrations.AddField(
            model_name='project',
            name='labs_tags',
            field=models.ManyToManyField(to='api.Labs'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='coe_tags',
            field=models.ManyToManyField(to='api.COE'),
        ),
    ]
