# Generated by Django 3.2.4 on 2021-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
